Repository ST-CK/Sturoom, pull requests merged in 2025-09, with the labels that each got.

#5 #5 [FIX] header.tsx 수정
  src/components/layout/Header.tsx
Labels: Test

#12 #12 [Design] 헤더 디자인 변경
  src/components/layout/Header.tsx
Labels: Design

#17 #17 [Fix] Header 수정
  src/components/layout/Header.tsx
Labels: Fix

#25 #25 [Make] 푸터 한번 더 수정합니다
  src/components/layout/Footer.tsx
Labels: Make

#48 #48 [Docs] 게시판 관련 파일 생성
  src/app/board/[id]/edit/page.tsx
  src/app/board/[id]/page.tsx
  src/app/board/new/page.tsx
  src/app/board/page.tsx
  src/components/board/BoardActions.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardForm.tsx
  src/components/board/BoardList.tsx
  src/services/board/boardRepo.mock.ts
  src/services/board/boardRepo.supabase.ts
  src/services/board/index.ts
  src/types/board.ts
Labels: Docs

#50 #50 [Design] 게시판 관련 파일 UI 코드 추가
  src/app/board/[id]/edit/page.tsx
  src/app/board/[id]/page.tsx
  src/app/board/new/page.tsx
  src/app/board/page.tsx
  src/components/board/BoardActions.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardForm.tsx
  src/components/board/BoardList.tsx
  src/services/board/boardRepo.mock.ts
  src/services/board/index.ts
  src/types/board.ts
Labels: Design

#53 #53[Feat] 로그인 유지 및 회원관리
  package-lock.json
  package.json
  src/app/mypage/page.tsx
  src/components/layout/Header.tsx
  src/hooks/hooks.txt
  src/hooks/useAuth.ts
Labels: Feat, Docs, Make

#66 #66 [Feat] 시간표 제작 및 db 연동
  .sql.txt
  src/app/mypage/page.tsx
  src/components/timetable/CourseForm.tsx
  src/components/timetable/TimetableGrid.tsx
  src/hooks/useAuth.ts
  src/lib/timetable.ts
  src/sql/test.txt
  src/sql/게시판.txt
  src/sql/회원가입.txt
Labels: Feat, Fix, Build, Docs, Remove
